project_name: bitcoind-metrics-exporter
force_token: gitea
gitea_urls:
  api: https://git.aads.cloud/api/v1/
  download: https://git.aads.cloud/

builds:
  - env:
      - CGO_ENABLED=0
    binary: bitcoind-metrics-exporter
    goos:
      - linux
    goarch:
      - amd64
      - arm64

nfpms:
  - package_name: bitcoind-metrics-exporter
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: aad
    homepage: https://git.aads.cloud/aad/bitcoind-metrics-exporter
    maintainer: Adriaan Conijn <adriaan.conijn@gmail.com>
    description: Prometheus/OpenTelemetry exporter for bitcoind metrics
    license: GPL-3.0
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: packaging/bitcoind-metrics-exporter.service
        dst: /lib/systemd/system/bitcoind-metrics-exporter.service
      - src: packaging/bitcoind-metrics-exporter.env
        dst: /etc/bitcoind-metrics-exporter/bitcoind-metrics-exporter.env
        type: config|noreplace
    scripts:
      postinstall: packaging/postinstall.sh
      preremove: packaging/preremove.sh
      postremove: packaging/postremove.sh

release:
  gitea:
    owner: aad
    name: bitcoind-metrics-exporter
